apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: flux-system  # Specify the flux-system namespace
data:
  index.html: |
    <html>
      <body>
        <h1>Welcome to Apache2</h1>
        <p>This is the Apache2-based HTML page.</p>
        <p>This is the second para</p>
        <p>This is the third para</p>
        <p>This is the fourth para</p>
      </body>
    </html>

