apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: flux-system
data:
  index.html: |
    <html>
      <body>
        <h1>Welcome to Innova Solutions GitOps Demo Page</h1>
        <p>This is the first commit dated May 15th </p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: flux-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: html-volume
          configMap:
            name: apache-config
---
apiVersion: v1
kind: Service
metadata:
  name: apache-loadbalancer
  namespace: flux-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: flux-system
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
