apiVersion: v1
kind: Service
metadata:
  name: apache-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Specify the Load Balancer type as "nlb" for Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalTrafficPolicy: Cluster  # Set the external traffic policy to "Cluster"
